### PR TITLE
Update ru_ru.json

### PR DESCRIPTION
**Pull request by TheDirectorX**

### CODE REVIEW

**Comment by TheDirectorX** [comment]
@Darkhax 
Quick questions:

1. **Curse of Ruin** will only work in anvil? After all, tools can also be repaired in **Grindstone**.
2. The description of the **Curse of Dullness** says that it lowers the attack damage of the **item**, but it can only be applied to **swords**. Do you want to add all the tools that have attack damage?

**Comment by Darkhax** [comment]
The curse of ruin only works in the anvil right now. Forge does not provide a way to work with the grindstone yet. 

The curse of dullness can be applied to any item however through vanilla mechanics it can only be applied to weapons which include axes as well as swords.

**Comment by TheDirectorX** [comment]
Why did I ask the second question? I saw in the JEI and checked in the anvil that other tools can't be enchanted by this curse. Only swords.
image

**Comment by Darkhax** [comment]
Oh I see, thank you for pointing that out. Vanilla hard-codes axes as being supported for sharpness and I missed that part. This will be fixed and I will merge the PR.

**Pull request merged**
